// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAgrdDxWgiDtty0lgY5tKW84tNWQpw8jQ',
    appId: '1:715649918086:web:775859b593fc7850379d07',
    messagingSenderId: '715649918086',
    projectId: 'handy-e3d10',
    authDomain: 'handy-e3d10.firebaseapp.com',
    storageBucket: 'handy-e3d10.firebasestorage.app',
    measurementId: 'G-6VQNTDL6T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNCyT1_25N0pVIHTdi9h5_w6w590d2DKA',
    appId: '1:715649918086:android:9765090b5af31cbb379d07',
    messagingSenderId: '715649918086',
    projectId: 'handy-e3d10',
    storageBucket: 'handy-e3d10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnIm7HiMYXXvv00CMcZVOwNC8GOWvDDn0',
    appId: '1:715649918086:ios:41de83b2ae10bc15379d07',
    messagingSenderId: '715649918086',
    projectId: 'handy-e3d10',
    storageBucket: 'handy-e3d10.firebasestorage.app',
    iosBundleId: 'com.example.handy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnIm7HiMYXXvv00CMcZVOwNC8GOWvDDn0',
    appId: '1:715649918086:ios:41de83b2ae10bc15379d07',
    messagingSenderId: '715649918086',
    projectId: 'handy-e3d10',
    storageBucket: 'handy-e3d10.firebasestorage.app',
    iosBundleId: 'com.example.handy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAgrdDxWgiDtty0lgY5tKW84tNWQpw8jQ',
    appId: '1:715649918086:web:b98537f65b08e3af379d07',
    messagingSenderId: '715649918086',
    projectId: 'handy-e3d10',
    authDomain: 'handy-e3d10.firebaseapp.com',
    storageBucket: 'handy-e3d10.firebasestorage.app',
    measurementId: 'G-KVHKQZE7MF',
  );
}
